### ISSUE TITLE
Change Bitcoin Cash logo to green instead of orange

### ISSUE THREAD

**Issue by cryptoeric** [bitcoincashorg/website#83]
Causes less confusion for noob and it looks better. Serves its purpose as cash better, too. Coinbase also has it officially listed in green

**Comment by omcnoe** [comment]
+1 in favor of changing the logo to green.

I know that BCH started with the orange logo, but I think that green:
- better represents CASH, has positive connotations with cash (greenbacks, positivity, success)
- differentiates BCH from BTC more strongly than the circle vs circle inside rectangle currently does
- is in line with styling already used by exchanges/community

Green is already widely used as BCH branding, I think it would be great if bitcoincash.org would adopt this design change.

**Comment by NxtChg** [comment]
Favor green logo/design too.

**Comment by ealmansi** [comment]
Not in favour.

Replacing the colour and design is a major change to the way in which Bitcoin Cash is perceived, and such a change should not be undertaken based solely on subjective remarks. That green looks better than orange and has more positive connotations is pure speculation based on subjective preference. At least until any evidence is provided.

Regarding widespread use of the green color to represent Bitcoin Cash. It'd be nice to see some concrete numbers. To me it seems that orange is still the norm, as seen in coinmarketcap.com, Bithumb (number 1 BCH exchange in terms of volume), Bittrex, and others.

Last, I'd like to point out that the argument that green is better suited to represent a currency might be very Western-centric due to the influence of the US dollar and use in mainstream Western media and film industry. It'd be nice to have some feedback from people with different backgrounds as to the truth of this statement. In particular, I believe bills are red in China. It also questionable whether we want Bitcoin Cash to be more strongly associated with fiat money, and the US dollar in particular.

**Comment by MohamedKiouaz** [comment]
Having multiple logo is a strong sign of decentralisation in my opinion.

**Comment by coinfeller** [comment]
I agree with Mohamed, personnally I prefer green but it's just my opinion. Some businesses have switched to green (Bitcoin.com and Coinbase), which I find it great because it helps users understand that there is a difference.

Local businesses tend to use orange which reminds of the Bitcoin color from what I've seen.

I think it's a strength to have this optionnality.

**Comment by zquestz** [comment]
@MohamedKiouaz I like your idea of adding it to the FAQ at a bare minimum. I personally am a fan of changing the logo, and have made my views clear in other posts. Changing the branding on the existing site is a big move, but at least mentioning that both green and orange logos are being used seems like a quality addition.

**Comment by Egon01** [comment]
Oh boy... I stick to orange 🍊

Bitcoin Cash is Bitcoin and Bitcoin was always orange. It is just a  matter of time until Core is losing its dominance and fading away as a collector's item for Core supporters.  

Merry Christmas ;)

**Comment by coinfeller** [comment]
merry Christmas !

**Comment by tofubear** [comment]
I'm cautious about changing colors. Given more time, the market will lean toward the best logo. If the majority of projects, wallets, exchanges, etc are using the same color we will know which is best for the org website. That being said, maybe those entities are not aware of the multiple logo colors/choices that exist? Would there be value in having a small logo album or package that contains the community's best logos and make them available in one place?

**Comment by fyookball** [comment]
Stick to orange.  I don't think there is consensus to change it on this website.

**Comment by salamidreng** [comment]
that what they need , the orange...
And
As long it start with Bit it will be orange to scam people

**Comment by schancel** [comment]
Orange performed several orders of magnitude better than green in AB testing twice.  Unless someone wants to build an evidence based case the the contrary, this issue should be closed as resolved.

![image](https://user-images.githubusercontent.com/213740/37191816-cbb36660-2316-11e8-99fb-fbc66c8a9d60.png)

**Comment by NxtChg** [comment]
@schancel > evidence

You keep using that word, I don't think it means what you think it means...
